name: Solidity Tests

on:
    push:
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '20.11.0'

            - name: Install Truffle
              run:
                npm install -g truffle
            
            - name: Install dependencies
              run: npm install

            - name: Compile contracts
              run: truffle compile

            - name: List files
              run: ls -R

            - name: Run tests
              run: truffle test